name: CI
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn lint
  test-plugin:
    name: Plugin Unit Tests
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn build && yarn ci-test 'yarn test-plugin'
  test-preview:
    name: E2E Tests - Preview
    runs-on: ubuntu-16.04
    steps:
      - uses: hmarr/debug-action@v1.0.0
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn build && yarn build-cli && yarn ci-test 'yarn test-preview'
  test-schema:
    name: Integration Tests - Schema
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn build && yarn ci-test 'yarn test-schema'
  test-build:
    name: Integration Tests - Build
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn build && yarn ci-test 'yarn test-build'
